version: '2'
services:
  virtuoso-dev:
    image: tenforce/virtuoso
    container_name: ontowiki-devenv-virtuoso-dev
    environment:
      DBA_PASSWORD: owdev
      SPARQL_UPDATE: "true"
    volumes:
      - /data
    ports:
      - "8890:8890"
      - "1111:1111"

  virtuoso-test:
    image: tenforce/virtuoso
    container_name: ontowiki-devenv-virtuoso-test
    environment:
      DBA_PASSWORD: owdev
      SPARQL_UPDATE: "true"
    volumes:
      - /data
    ports:
      - "8891:8890"
      - "1112:1111"

  mysql-dev:
    image: mysql
    container_name: ontowiki-devenv-mysql-dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: php
      MYSQL_PASSWORD: owdev
      MYSQL_DATABASE: ontowiki-dev
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"

  mysql-test:
    image: mysql
    container_name: ontowiki-devenv-mysql-test
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: php
      MYSQL_PASSWORD: owdev
      MYSQL_DATABASE: ow_TEST
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"

  stardog-dev:
    image: aksw/dld-store-stardog
    container_name: ontowiki-devenv-stardog-dev
    volumes:
      - /stardog
    ports:
      - "5820:5820"
      - "8080:80"

  stardog-test:
    image: aksw/dld-store-stardog
    container_name: ontowiki-devenv-stardog-test
    volumes:
      - /stardog
    ports:
      - "5821:5820"
      - "8081:80"

  phpserver:
    build: ./docker/php
    image: ontowiki-devenv/phpserver
    container_name: ontowiki-devenv-phpserver
    volumes:
      - ./..:/var/www
    links:
      - virtuoso-dev
      - mysql-dev
      - stardog-dev

  nginx:
    build: ./docker/nginx
    image: ontowiki-devenv/nginx
    container_name: ontowiki-devenv-nginx
    volumes:
      - ./..:/var/www
    links:
      - phpserver
    ports:
      - "80:80"