virtuoso-dev:
  image: tenforce/virtuoso
  environment:
    DBA_PASSWORD: owdev
    SPARQL_UPDATE: "true"
  volumes:
    - /data
  ports:
    - "8890:8890"
    - "1111:1111"

virtuoso-test:
  image: tenforce/virtuoso
  environment:
    DBA_PASSWORD: owdev
    SPARQL_UPDATE: "true"
  volumes:
    - /data
  ports:
    - "8891:8890"
    - "1112:1111"

mysql-dev:
  image: mysql
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_USER: php
    MYSQL_PASSWORD: owdev
    MYSQL_DATABASE: ontowiki-dev
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"

mysql-test:
  image: mysql
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_USER: php
    MYSQL_PASSWORD: owdev
    MYSQL_DATABASE: ow_TEST
  volumes:
    - /var/lib/mysql
  ports:
    - "3307:3306"

phpserver:
  build: ./docker/php
  volumes:
    - ./..:/var/www
  links:
    - virtuoso-dev
    - mysql-dev

nginx:
  build: ./docker/nginx
  volumes:
    - ./..:/var/www
  links:
    - phpserver
  ports:
    - "80:80"